### ISSUE TITLE
Colaboración

### ISSUE THREAD

**Issue by aronzillo** [gmlo89/CFDI#1]
Hola, me gustaría colaborar con el proyecto, ¿cómo le hacemos?

**Comment by gmlo89** [comment]
Hola, disculpa no se por que no había visto esto. Si aun estas interesado en los proximos días subire una actualización y puedes revisarlo y mandar un pull request.

**Comment by aronzillo** [comment]
> Hola, disculpa no se por que no había visto esto. Si aun estas interesado en los proximos días subire una actualización y puedes revisarlo y mandar un pull request.

Perfecto, estaré al pendiente de dicha actualización.
